// Code generated by Microsoft (R) AutoRest Code Generator 1.1.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lykke.Service.Affiliate.Client.AutorestClient.Models
{
    using Lykke.Service;
    using Lykke.Service.Affiliate;
    using Lykke.Service.Affiliate.Client;
    using Lykke.Service.Affiliate.Client.AutorestClient;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class LinkModel
    {
        /// <summary>
        /// Initializes a new instance of the LinkModel class.
        /// </summary>
        public LinkModel()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the LinkModel class.
        /// </summary>
        public LinkModel(string url = default(string), string redirectUrl = default(string))
        {
            Url = url;
            RedirectUrl = redirectUrl;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Url")]
        public string Url { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "RedirectUrl")]
        public string RedirectUrl { get; set; }

    }
}
