// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.Affiliate.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ReferralModel
    {
        /// <summary>
        /// Initializes a new instance of the ReferralModel class.
        /// </summary>
        public ReferralModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ReferralModel class.
        /// </summary>
        public ReferralModel(System.DateTime createdDt, string id = default(string))
        {
            Id = id;
            CreatedDt = createdDt;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CreatedDt")]
        public System.DateTime CreatedDt { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
