// Code generated by Microsoft (R) AutoRest Code Generator 1.1.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lykke.Service.Affiliate.Client.AutorestClient.Models
{
    using Lykke.Service;
    using Lykke.Service.Affiliate;
    using Lykke.Service.Affiliate.Client;
    using Lykke.Service.Affiliate.Client.AutorestClient;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class StatisticItemModel
    {
        /// <summary>
        /// Initializes a new instance of the StatisticItemModel class.
        /// </summary>
        public StatisticItemModel()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the StatisticItemModel class.
        /// </summary>
        public StatisticItemModel(double tradeVolume, double bonusVolume, string assetId = default(string))
        {
            AssetId = assetId;
            TradeVolume = tradeVolume;
            BonusVolume = bonusVolume;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AssetId")]
        public string AssetId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TradeVolume")]
        public double TradeVolume { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "BonusVolume")]
        public double BonusVolume { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
